import { SessionProvider } from 'next-auth/react';

import type { Metadata } from 'next';
// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
import { Session } from 'next-auth';
import { Inter } from 'next/font/google';
import { headers } from 'next/headers';

import { AuthContext } from './AuthContext';
import './globals.css';

import { getServerSession } from '@/lib/auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  console.log('root layout', { session });
  return (
    <html lang="en">
      <head />
      <body>
      <AuthContext session={session}>{children}</AuthContext>
        
        {/* <App */}
        

        {/* Hello World */}
        {/* <AuthContext session={session}>{children}</AuthContext> */}
      </body>
    </html>
  );
}
